---@meta

---@class UWBP_Modern_Settings_SaveLoadPage_C : UVAltarWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field VPauseMenuViewModel UVPauseMenuViewModel
---@field SaveLoadSlideInOut UWidgetAnimation
---@field saveload_popup_sizebox USizeBox
---@field settings_system_load_button UWBP_Modern_Settings_SystemButtonWrapper_C
---@field settings_system_mainMenu_button UWBP_Modern_Settings_SystemButtonWrapper_C
---@field settings_system_quicksave_button UWBP_Modern_Settings_SystemButtonWrapper_C
---@field settings_system_quit_button UWBP_Modern_Settings_SystemButtonWrapper_C
---@field settings_system_save_button UWBP_Modern_Settings_SystemButtonWrapper_C
---@field Popup UWBP_Modern_Settings_SaveLoadPopup_C
---@field MainMenuPopupText FText
---@field QuitGamePopupText FText
---@field Buttons TArray<UWBP_Modern_Settings_SystemButtonWrapper_C>
---@field FocusIndex int32
local UWBP_Modern_Settings_SaveLoadPage_C = {}

---@return boolean
function UWBP_Modern_Settings_SaveLoadPage_C:DoesAllowNavigation() end
---@param Value boolean
function UWBP_Modern_Settings_SaveLoadPage_C:IsPageInteractible(Value) end
function UWBP_Modern_Settings_SaveLoadPage_C:CreateButtonArray() end
function UWBP_Modern_Settings_SaveLoadPage_C:HandleQuitButtonVisibility() end
---@param Test boolean
function UWBP_Modern_Settings_SaveLoadPage_C:ThisIsForPluginCompliance(Test) end
---@return UWidget
function UWBP_Modern_Settings_SaveLoadPage_C:BP_GetDesiredFocusTarget() end
function UWBP_Modern_Settings_SaveLoadPage_C:OnFocus() end
function UWBP_Modern_Settings_SaveLoadPage_C:Construct() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_quit_button_K2Node_ComponentBoundEvent_1_OnButtonClicked__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_mainMenu_button_K2Node_ComponentBoundEvent_2_OnButtonClicked__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_mainMenu_button_K2Node_ComponentBoundEvent_4_OnButtonFocussed__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_quit_button_K2Node_ComponentBoundEvent_5_OnButtonFocussed__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_quicksave_button_K2Node_ComponentBoundEvent_8_OnButtonClicked__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_quicksave_button_K2Node_ComponentBoundEvent_9_OnButtonFocussed__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_load_button_K2Node_ComponentBoundEvent_6_OnButtonClicked__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_save_button_K2Node_ComponentBoundEvent_7_OnButtonClicked__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_save_button_K2Node_ComponentBoundEvent_0_OnButtonFocussed__DelegateSignature() end
function UWBP_Modern_Settings_SaveLoadPage_C:BndEvt__WBP_Modern_Settings_SaveLoadPage_settings_system_load_button_K2Node_ComponentBoundEvent_3_OnButtonFocussed__DelegateSignature() end
---@param EntryPoint int32
function UWBP_Modern_Settings_SaveLoadPage_C:ExecuteUbergraph_WBP_Modern_Settings_SaveLoadPage(EntryPoint) end


